# Generated by Django 4.2.1 on 2023-06-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="menuData",
            fields=[
                (
                    "date",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("lunch_menu_and_allergy", models.CharField(max_length=128, null=True)),
                (
                    "dinner_menu_and_allergy",
                    models.CharField(max_length=128, null=True),
                ),
            ],
        ),
    ]
