# Generated by Django 4.2.1 on 2023-07-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodApp", "0002_lunchvoteusers_dinnervoteusers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menudata",
            name="dinner_menu_and_allergy",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="menudata",
            name="lunch_menu_and_allergy",
            field=models.TextField(null=True),
        ),
    ]
