# Generated by Django 4.2.1 on 2023-06-03 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0002_alter_customuser_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="barcode_img",
        ),
    ]
