# Generated by Django 4.2.1 on 2023-06-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_remove_customuser_barcode_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='이름', max_length=10, verbose_name='본명'),
            preserve_default=False,
        ),
    ]
