# Generated by Django 4.2.1 on 2023-06-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardmodel",
            name="board_EN",
            field=models.CharField(default="board", max_length=50),
            preserve_default=False,
        ),
    ]
