# Generated by Django 4.2.1 on 2023-06-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("boardApp", "0003_boardmodel_level_boardmodel_lft_boardmodel_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="parent_comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boardApp.commentmodel",
            ),
        ),
    ]
