# Generated by Django 4.2.1 on 2023-06-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("boardApp", "0005_vote_voteitem_voteusers"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentmodel",
            name="vote",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boardApp.vote",
            ),
        ),
    ]
