# Generated by Django 4.2.1 on 2023-06-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardApp", "0007_alter_contentmodel_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentmodel",
            name="liked_users",
            field=models.TextField(default=""),
        ),
    ]
