# Generated by Django 4.2.1 on 2023-07-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0008_contentmodel_liked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boardApp.vote'),
        ),
    ]
