# Generated by Django 4.2.1 on 2023-07-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardApp", "0009_alter_contentmodel_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentmodel",
            name="isNotice",
            field=models.BooleanField(default=False),
        ),
    ]
