# Generated by Django 4.2.1 on 2023-07-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardApp", "0010_contentmodel_isnotice"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentmodel",
            name="IsDeleted",
            field=models.BooleanField(default=False),
        ),
    ]
