# Generated by Django 4.2.1 on 2023-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="eventModel",
            fields=[
                (
                    "date",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("eventName", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=15)),
            ],
        ),
    ]
